version: "3.8"
services:
  devkit:
    build: .
    volumes:
      - ./projects:/projects
      - ./config.yaml:/root/.config/code-server/config.yaml
      - ./bashrc:/root/.bashrc
      - ./settings.json:/root/.local/share/code-server/User/settings.json
    ports:
      - "3000:3000"
      - "8080:8080"
      - "9090:9090"